---
abstract: 'Perl module for the Philips Hue light system'
author:
  - 'Alessandro Zummo <a.zummo@towertech.it>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Hue
requires:
  Carp: 0
  Class::Accessor: 0
  Data::Dumper: 0
  Hash::Merge::Simple: 0
  IO::Select: 0
  IO::Socket::Multicast: 0
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moo: 0
  base: 0
  common::sense: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dwery/hue-perl/issues
  repository: git://github.com/dwery/hue-perl.git
version: 0.4
